### ISSUE TITLE
json icon break

### ISSUE THREAD

**Issue by DinkyTrady** [DaikyXendo/nvim-material-icon#2]
i found this the bufferline and lualine
![Uploading Screenshot_2022-11-21-19-45-59-049_com.termux.jpg…]()

here is the the neo-tree
![Screenshot_2022-11-21-19-46-03-658_com termux](https://user-images.githubusercontent.com/111265264/203059410-77787f0c-fb78-4998-bc13-c7b526894143.jpg)

i hope you will fix this issue

**Comment by PyDev19** [comment]
Hey I found a fix for the issue.
Looking at the nerd fonts website, they seem to be using a removed json glyph. If you want the same one it is now this:
`󰘦`

**Comment by DinkyTrady** [comment]
> Hey I found a fix for the issue. Looking at the nerd fonts website, they seem to be using a removed json glyph. If you want the same one it is now this: `󰘦`

thx for the info mate (too late💀)
this repo is not maintained again and i'm go with devicons
