### ISSUE TITLE
Icon for .age files

### ISSUE THREAD

**Issue by mrjones2014** [DaikyXendo/nvim-material-icon#5]
.age files contain encrypted contents, to be decrypted with the [age](https://github.com/FiloSottile/age) CLI.

**Comment by DaikyXendo** [comment]
Sorry, I couldn't find a nerd icon for this file extension. Can you suggest me nerd icon and color? Thank!

**Comment by mrjones2014** [comment]
How about `nf-cod-gist_secret` for the icon and a shade of yellow for the color?

**Comment by DaikyXendo** [comment]
In the latest version, the icon you requested has been added! Thank!
